<a href="https://colab.research.google.com/github/ujjwalbasnyat/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr5 = np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr6 = np.arange(10,20,3)
arr6

array([10, 13, 16, 19])

In [ ]:
arr7 = arr6.copy()
arr7

array([10, 13, 16, 19])

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr8 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr8.shape

(2, 2, 3)

In [ ]:
arr8.ndim

3

In [ ]:
arr9 = np.arange(18).reshape(6,3)
arr9

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
arr9[2:4]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr9[-1]

array([15, 16, 17])

In [ ]:
arr9.T

array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]])

In [ ]:
arr9.T[:,2:4]

array([[ 6,  9],
       [ 7, 10],
       [ 8, 11]])