<a href="https://colab.research.google.com/github/ujjwalbasnyat/numpy/blob/branch1/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Array

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr5 = np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr6 = np.arange(10,20,3)
arr6

array([10, 13, 16, 19])

In [ ]:
arr7 = arr6.copy()
arr7

array([10, 13, 16, 19])

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr8 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr8.shape

(2, 2, 3)

In [ ]:
arr8.ndim

3

# Slicing

In [32]:
arr9 = np.arange(24).reshape(6,4)
arr9

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr9[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr9[-1]

array([20, 21, 22, 23])

In [ ]:
arr9.T

array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]])

In [ ]:
arr9.T[:,2:4]

array([[ 8, 12],
       [ 9, 13],
       [10, 14],
       [11, 15]])

In [ ]:
arr9

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr9[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [ ]:
arr9[4:,2:]

array([[18, 19],
       [22, 23]])

# Iteration

In [ ]:
arr9

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
for i in arr9:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [ ]:
for i in np.nditer(arr9):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# Operations

In [ ]:
arr10 = np.array([1,2,3,4,5,6])
arr11 = np.array([4,5,6,7,8,9])

In [ ]:
arr10+arr11

array([ 5,  7,  9, 11, 13, 15])

In [ ]:
# scalar multipication of vector
arr10*2

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
arr10>3

array([False, False, False,  True,  True,  True])

In [ ]:
# dot product of matrices
arr12 = np.arange(6).reshape(3,2)
arr13 = np.arange(3,9).reshape(2,3)

In [ ]:
arr12.dot(arr13)

array([[ 6,  7,  8],
       [24, 29, 34],
       [42, 51, 60]])

In [ ]:
arr12

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr12.min(axis=1)

array([0, 2, 4])

In [ ]:
arr12.sum(axis=0)

array([6, 9])

In [ ]:
arr12.sum()

15

In [ ]:
arr12.mean()

2.5

In [ ]:
np.median(arr12)

2.5

In [ ]:
arr12.std()

1.707825127659933

In [ ]:
np.sin(arr12)

array([[ 0.        ,  0.84147098],
       [ 0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427]])

In [ ]:
np.exp(arr12)

array([[  1.        ,   2.71828183],
       [  7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 ]])

# Reshaping

In [7]:
arr13 = np.arange(12).reshape(2,2,3)
arr13

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [8]:
# ravel() function helps to convert higher Dimensional array into 1D
arr13.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
# Transpose
arr13.transpose()

array([[[ 0,  6],
        [ 3,  9]],

       [[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]]])

In [11]:
arr13.transpose().shape

(3, 2, 2)

In [13]:
# Stacking helps to merge two arrays into single array
arr14 = np.arange(12,24).reshape(2,2,3)
arr14

array([[[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [16]:
# hstack merge arrays horizontally whereas vstack merge vertically
np.hstack((arr13,arr14))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [12, 13, 14],
        [15, 16, 17]],

       [[ 6,  7,  8],
        [ 9, 10, 11],
        [18, 19, 20],
        [21, 22, 23]]])

In [17]:
# Splitting array
arr13

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [26]:
arr15 = np.array([[1,2],[0,1]])
arr15

array([[1, 2],
       [0, 1]])

In [28]:
np.hsplit(arr15,2)

[array([[1],
        [0]]),
 array([[2],
        [1]])]

# Fancy indexing

In [33]:
arr9

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [34]:
arr9[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])